#! /bin/bash

vagrant up oob-mgmt-server oob-mgmt-switch netq-ts
vagrant up rtr01 rtr02
vagrant up edge01 edge02
vagrant up super02 super01
vagrant up spine01 spine02 spine03 spine04
vagrant up leaf01 leaf02 leaf03 leaf04
vagrant up leaf05 leaf06 leaf07 leaf08
vagrant up exit01 exit02 exit03 exit04
vagrant up server01 server02 server03 server04
vagrant up server05 server06 server07 server08
vagrant up server09 server10 server11 server12

