---
- hosts: oob 
  become: true
  roles:
  - oob-mgmt-server
  - app-netq

- hosts: netq-ts
  become: true
  roles:
  - setup-netq-ts
  - app-grafana
  - app-netbox

- hosts: spines,superspine
  become: true
  roles:
  - setup-switch
  - switch-spine

- hosts: leafs,edge,router
  become: true 
  roles:
  - setup-switch
  - switch-leaf

- hosts: servers-rack1,servers-rack3 
  become: true 
  roles:
  - setup-server
  - app-netq
  - server-multitenant

- hosts: servers-rack2 
  become: true 
  roles:
  - setup-server
  - app-netq
  - server-evpn
  tasks:
  - name: reboot
    reboot:
      reboot_timeout: 1200
      test_command: mount
...
