---
- name: Install Python3-pip 
  apt:
    name: python3-pip
    update_cache: yes

- name: Install Pyyaml
  command: pip3 install PyYAML

- name: Install Pynetbox
  command: pip3 install pynetbox==3.4.7 
...
