---
- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present

- name: Add Cumulus Repo
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb xenial netq-1.4
    state: present
    update_cache: no

- name: Install Python3-pip 
  apt:
    name: python3-pip
    update_cache: yes

- name: Install Pyyaml
  command: pip3 install PyYAML

- name: Install Pynetbox
  command: pip3 install pynetbox==3.4.7 

- name: Install NetQ
  apt:
    name: cumulus-netq
    update_cache: yes

- name: copy netq config file
  copy:
    src: netq.yml
    dest: /etc/netq/netq.yml

- name: Enable and start netqd 
  command: "{{item}}"
  with_items:
    - systemctl stop netqd
    - systemctl enable netqd
    - systemctl start netqd

- name: Enable and start netq-agent
  command: "{{item}}"
  with_items:
    - systemctl stop netq-agent
    - systemctl enable netq-agent
    - systemctl start netq-agent

- name: Pause to let NetQ service to start
  pause:
    seconds: 5

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted
...
