#
# prep the servers for doing fun stuff :-)
#

- set_fact:
    myvars: "{{ servervars[inventory_hostname] }}"

- name: add repositories for NetQ/HostPack, Mesosphere, Docker and then update the apt cache
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A88BBC95
- apt:
    name: ubuntu-cloud-keyring
    state: present
- apt_repository:
    repo: 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu bionic-updates/rocky  main'
    filename: rocky
    state: present
- apt:
    update_cache: yes

# These packages redundantly  appear in later playbooks
#
- name: install common OpenStack packages to speed up the deployment
  apt:
    name: ['python-openstackclient', 'neutron-linuxbridge-agent', 'neutron-l3-agent', 'nova-common']

- name: high speed networking
  copy:
    src: 99cumulus_defaults
    dest: /etc/sysctl.d/99cumulus_defaults.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
- command: 'sysctl --system'
